name: Trigger Environment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Print
        run: echo "Triggering environment visibility"
